on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
      ./.build/makePages.sh
      git config --global user.name "GitHub Action"
      git config --global user.email "action@github.com"
      git add -A
      git commit -m "Built pages"

    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
